version: "3.8"

services:
  psql-db:
    build:
     context: .
     dockerfile: Dockerfile.db
     
    container_name: rental_postgres_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Awale123
      - POSTGRES_DB=Rental
    ports:
      - '5432:5432'

  app:
    container_name: rental_spring_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/Rental
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Awale123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
